void Connect_WiFi();
void Init_MQTT();
void Print_WiFi_Status();
void Check_WiFi_Server();
void Setup_sensors();
void Read_Sensors();
void Read_MHZ14A();
void Calibrate_MHZ14A();
void Read_SCD30();
void Calibrate_SCD30();
void SCD30_Do_AutoSelfCalibration();
void SCD30_Do_Temperature_Offset();
void SCD30_Do_Measurement_Interval();
void SCD30_Do_Forced_Calibration_Factor();
void SCD30_Do_Altitude_Compensation();
void SCD30DeviceInfo();
void Evaluate_CO2_Value();
void Read_DHT11();
void Send_Message_Cloud_App_MQTT();
void Receive_Message_Cloud_App_MQTT(char* topic, byte* payload, unsigned int length);
void MQTTReconnect();
void push_button_handler();
void changeState_CO2_STATUS_BUILTIN_LED_GPIO();
void changeState_BUZZER_GPIO();
void update_OLED_CO2();
void update_OLED_Status();
void Read_EEPROM();
void Write_EEPROM();
void Wipe_EEPROM();
void Print_Config();
void firmware_update();
void update_started();
void update_finished();
void update_progress(int cur, int total);
void update_error(int err);